name: Publish Docker image

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: corinnekrych/demo-sprint58
          tags: $GITHUB_SHA 

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy artifact to CBP
        uses: cloudbees-gha-cbp/register-build-artifact@main 
        with:
          component-id: "1541ff41-3361-4159-b594-27142bd69baf"
          name: "demo-sprint58-artifact"
          version: "1.0.0"
          url: "docker.io/corinnekrych/demo-sprint58:$GITHUB_SHA"
          digest: "sha256:4e9519c943cbd59c87044a943a1adab591c4923ca016879406d71aea4370b093"
          cloudbees-url: ${{ vars.CLOUDBEES_PLATFORM_URL }}
          cloudbees-pat: ${{ secrets.CLOUDBEES_PLATFORM_PAT }}          